#!/usr/bin/env bash
#
# Copyright (c) Jonathan M. Lange, 2016. Made available under the Apache 2
# license.
#
# Build a minimal Docker image for our binary.
#
# Run with:
#   build-image /path/to/binary image-name image-tag

{% raw %}

set -o errexit
set -o nounset
set -o pipefail

# The name of the image where the binary was built. We use this image to look
# up shared library dependencies with 'ldd', and we copy those libraries from
# this image.
#
# Assumes the image has 'ldd' installed on the path.
BUILD_IMAGE="fpco/stack-build:lts-7.2" # XXX: Make this a parameter?

# Dependencies
DOCKER=docker
AWK=awk
GREP=grep
CP=cp
MKDIR=mkdir
TAR=tar

# Path to a Linux binary that we're going to run in the container.
binary_path="${1}"
# The name of the image to make.
image_name="${2}"
# How to tag the image when we're done. We'll also make a 'latest' tag.
image_tag="${3}"

exe_name=$(basename "${binary_path}")

# Run a container for the build image so we can copy things into and out of it.
build_container=$("${DOCKER}" run -d "${BUILD_IMAGE}" tail -f /dev/null)
trap '"${DOCKER}" stop "${build_container}" >/dev/null' EXIT

# Copy the built binary to the build container so we can identify libraries
"${DOCKER}" cp "${binary_path}" "${build_container}:/${exe_name}"

# Identify linked libraries
libraries=( $( "${DOCKER}" exec "${build_container}" ldd "/${exe_name}" | "${AWK}" '{print $(NF-1)}' | "${GREP}" -v '=>' ) )
libraries+=('/bin/sh')

# Create temporary directory for building up new container.
run_container_dir=$(mktemp -d 2>/dev/null || mktemp -d -t "${exe_name}")

# Copy executable and all needed libraries into temporary directory.
"${CP}" "${binary_path}" "${run_container_dir}/${exe_name}"
for lib in "${libraries[@]}"; do
    "${MKDIR}" -p "${run_container_dir}/$(dirname "$lib")"
    # Need -L to make sure we get actual libraries & binaries, not symlinks to
    # them.
    "${DOCKER}" cp -L "${build_container}:${lib}" "${run_container_dir}/${lib}"
done

"${TAR}" -C "${run_container_dir}" -c . | "${DOCKER}" import --change "ENTRYPOINT [\"/${exe_name}\"]" - "${image_name}"
"${DOCKER}" tag "${image_name}" "${image_name}:${image_tag}"
echo "${image_name}:${image_tag}"

{% endraw %}
